In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("nasa.csv")

In [4]:
data.columns

Index(['Neo Reference ID', 'Name', 'Absolute Magnitude', 'Est Dia in KM(min)',
       'Est Dia in KM(max)', 'Close Approach Date',
       'Epoch Date Close Approach', 'Relative Velocity km per sec',
       'Miss Dist.(Astronomical)', 'Miss Dist.(lunar)',
       'Miss Dist.(kilometers)', 'Orbit ID', 'Orbit Determination Date',
       'Orbit Uncertainity', 'Minimum Orbit Intersection',
       'Jupiter Tisserand Invariant', 'Epoch Osculation', 'Eccentricity',
       'Semi Major Axis', 'Inclination', 'Asc Node Longitude',
       'Orbital Period', 'Perihelion Distance', 'Perihelion Arg',
       'Aphelion Dist', 'Perihelion Time', 'Mean Anomaly', 'Mean Motion',
       'Equinox', 'Hazardous'],
      dtype='object')

In [9]:
data.rename(
    columns={"Est Dia in KM(min)": "Estimated Diameter in Kilometers (min)",
             "Est Dia in KM(max)": "Estimated Diameter in Kilometers (max)",
             "Relative Velocity km per sec": "Relative Velocity (km/s)", 
             "Miss Dist.(Astronomical)": "Miss Distance in Astronimical Units (AU)",
             "Miss Dist.(lunar)": "Miss Distance in Lunar Distance (LD)",
             "Miss Dist.(kilometers)": "Miss Distance in Kilometers",
             "Asc Node Longitude": "Ascending Node Longitude",
             "Perihelion Arg": "Perihelion Argument",
             "Aphelion Dist": "Aphelion Distance",
             "Eccentricity": "Orbit Eccentricity",
             "Semi Major Axis": "Orbit Semi-Major Axis",
             "Inclination": "Orbit Inclination"},
    inplace=True,
)

In [10]:
data.columns

Index(['Neo Reference ID', 'Name', 'Absolute Magnitude',
       'Estimated Diameter in Kilometers (min)',
       'Estimated Diameter in Kilometers (max)', 'Close Approach Date',
       'Epoch Date Close Approach', 'Relative Velocity (km/s)',
       'Miss Distance in Astronimical Units (AU)',
       'Miss Distance in Lunar Distance (LD)', 'Miss Distance in Kilometers',
       'Orbit ID', 'Orbit Determination Date', 'Orbit Uncertainity',
       'Minimum Orbit Intersection', 'Jupiter Tisserand Invariant',
       'Epoch Osculation', 'Orbit Eccentricity', 'Orbit Semi-Major Axis',
       'Orbit Inclination', 'Ascending Node Longitude', 'Orbital Period',
       'Perihelion Distance', 'Perihelion Argument', 'Aphelion Distance',
       'Perihelion Time', 'Mean Anomaly', 'Mean Motion', 'Equinox',
       'Hazardous'],
      dtype='object')

In [13]:
data

,Neo Reference ID,Name,Absolute Magnitude,Estimated Diameter in Kilometers (min),Estimated Diameter in Kilometers (max),Close Approach Date,Epoch Date Close Approach,Relative Velocity (km/s),Miss Distance in Astronimical Units (AU),Miss Distance in Lunar Distance (LD),...,Ascending Node Longitude,Orbital Period,Perihelion Distance,Perihelion Argument,Aphelion Distance,Perihelion Time,Mean Anomaly,Mean Motion,Equinox,Hazardous
0,3703080,3703080,21.600,0.127220,0.284472,1995-01-01,788947200000,6.115834,0.419483,163.178711,...,314.373913,609.599786,0.808259,57.257470,2.005764,2.458162e+06,264.837533,0.590551,J2000,True
1,3723955,3723955,21.300,0.146068,0.326618,1995-01-01,788947200000,18.113985,0.383014,148.992630,...,136.717242,425.869294,0.718200,313.091975,1.497352,2.457795e+06,173.741112,0.845330,J2000,False
2,2446862,2446862,20.300,0.231502,0.517654,1995-01-08,789552000000,7.590711,0.050956,19.821890,...,259.475979,643.580228,0.950791,248.415038,1.966857,2.458120e+06,292.893654,0.559371,J2000,True
3,3092506,3092506,27.400,0.008801,0.019681,1995-01-15,790156800000,11.173874,0.285322,110.990387,...,57.173266,514.082140,0.983902,18.707701,1.527904,2.457902e+06,68.741007,0.700277,J2000,False
4,3514799,3514799,21.600,0.127220,0.284472,1995-01-15,790156800000,9.840831,0.407832,158.646713,...,84.629307,495.597821,0.967687,158.263596,1.483543,2.457814e+06,135.142133,0.726395,J2000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,3759007,23.900,0.044112,0.098637,2016-09-08,1473318000000,22.154265,0.041361,16.089413,...,164.183305,457.179984,0.741558,276.395697,1.581299,2.457708e+06,304.306025,0.787436,J2000,False
4683,3759295,3759295,28.200,0.006089,0.013616,2016-09-08,1473318000000,3.225150,0.006469,2.516399,...,345.225230,407.185767,0.996434,42.111064,1.153835,2.458088e+06,282.978786,0.884117,J2000,False
4684,3759714,3759714,22.700,0.076658,0.171412,2016-09-08,1473318000000,7.191642,0.061009,23.732393,...,37.026468,690.054279,0.965760,274.692712,2.090708,2.458300e+06,203.501147,0.521698,J2000,False
4685,3759720,3759720,21.800,0.116026,0.259442,2016-09-08,1473318000000,11.352090,0.260760,101.435493,...,163.802910,662.048343,1.185467,180.346090,1.787733,2.458288e+06,203.524965,0.543767,J2000,False
4686,3772978,3772978,19.109,0.400641,0.895860,2016-09-08,1473318000000,35.946852,0.462372,179.862671,...,187.642183,653.679098,0.876110,222.436688,2.071980,2.458319e+06,184.820424,0.550729,J2000,False

In [12]:
data.to_csv("nasa.csv")